sudo: required
language: go
go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"

matrix:
  allow_failures:
  - go: tip

env:
  - GO111MODULE=on
  - GO111MODULE=off

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

install:
  - GOPROXY=https://proxy.golang.org go get -t -v ./...

before_script:
  # Generate mocks of latest AWS SDK APIs.
  - GOPROXY=https://proxy.golang.org go get -u github.com/vektra/mockery/cmd/mockery
  - go generate ./...

script:
  - go test -race -timeout 5m -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
