sudo: required
language: go
services:
  - docker

matrix:
  include:
    - go: "1.11.x"
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
    - go: "1.12.x"
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
  allow_failures:
  - go: tip

env:
  - GO111MODULE=on
  - GO111MODULE=off

addons:
  apt:
    update: true
    packages:
    - docker-ce

before_install:
  - sudo sysctl -w vm.max_map_count=262144

install:
  - go get -t -v ./...

before_script:
  # Generate mocks of latest AWS SDK APIs.
  - go get -u github.com/vektra/mockery/cmd/mockery
  - go generate ./...

script:
  - go test -race -timeout 5m -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
