sudo: required
language: go
go:
  - "1.11.x"
  - "1.12.x"
services:
  - docker

matrix:
  allow_failures:
  - go: tip

env:
  - GO111MODULE=on
  - GO111MODULE=off

addons:
  apt:
    update: true
    packages:
    - docker-ce

before_install:
  - sudo sysctl -w vm.max_map_count=262144

install:
  - go get -t -v ./...

script:
  - go test -race -timeout 5m ./...
