version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.1.0
    hostname: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - network.publish_host=127.0.0.1
      - logger.org.elasticsearch=warn
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - path.repo=/tmp
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  wait:
    image: waisbrot/wait
    links:
      - elasticsearch
    environment:
      - TARGETS=elasticsearch:9200
      - TIMEOUT=60
